------------------------------------------------------
-- Autor       : IES HERMANOS MACHADO
-- Descripción : Script CREACION TABLESPACE Y USUARIO - PROYECTO BBDD
-- Responsables : Fernando Márquez Rodríguez , Rafael José Ossorio Lopéz, Victor Carrasco Artacho, Carlos González Ruiz, Gabriel Rodríguez Félix 
------------------------------------------------------

CREATE TABLE DEPARTAMENTO(

COD_DEPARTAMENTO NUMBER(4),
ESPECIALIDAD     VARCHAR2(50),
EMPLEADO_JEFE    NUMBER(6)
    

);

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT DEPARTAMENTO_PK_COD_DEPT PRIMARY KEY (COD_DEPARTAMENTO)
ADD CONSTRAINT DEPARTAMENTO_FK_JEFE FOREIGN KEY (EMPLEADO_JEFE) REFERENCES EMPLEADO(CODEMPLEADO)
ADD CONSTRAINT DEPARTAMENTO_UQ_ESPECIALIDAD UNIQUE (ESPECIALIDAD)
ADD CONSTRAINT DEPARTAMENTO_UQ_EMPLEADO_JEFE UNIQUE (EMPLEADO_JEFE);

CREATE SEQUENCE SEQ_COD_DEPARTAMENTO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
;