/*CREAMOS EL TABLESPACE CON EL SYS PARA LUEGO PONERSELO AL USUARIO*/
CREATE TABLESPACE PROYECTO_BBDD_DUAL_DATOS DATAFILE
'C:\oraclexe\app\oracle\oradata\XE\PROYECTO_BBDD_DATOS.dbf'
SIZE 100M 
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

alter session set "_ORACLE_SCRIPT"=true;

/*CREAMOS EL USUARIO CON EL TABLESPACE CREADO*/
CREATE USER ADMIN_GEST_ENERG IDENTIFIED BY ROOTROOT DEFAULT TABLESPACE PROYECTO_BBDD_DUAL_DATOS;

/*LE DAMOS LOS PERMISOS AL USUARIO*/
GRANT CREATE SESSION, ALTER SESSION, CREATE TABLE, CREATE SEQUENCE,
CREATE TABLESPACE, UNLIMITED TABLESPACE TO ADMIN_GEST_ENERG;

