------------------------------------------------------
-- Autor       : IES HERMANOS MACHADO
<<<<<<< HEAD
-- Descripci�n : Script 2 CREACION TABLA CONTRATO - PROYECTO BBDD
-- Responsables : Fernando M�rquez Rodr�guez , Rafael Jos� Ossorio Lop�z, Victor Carrasco Artacho, Carlos Gonz�lez Ruiz, Gabriel Rodr�guez F�lix 
=======
-- Descripcion : Script 2 CREACION TABLA DEPARTAMENTO - PROYECTO BBDD
-- Responsables : Fernando Marquez Rodriguez , Rafael Jose Ossorio Lopez, Victor Carrasco Artacho, Carlos Gonzalez Ruiz, Gabriel Rodriguez Felix 
>>>>>>> 73c889bdad7eecd310e61902209583bfc945827a
------------------------------------------------------

CREATE TABLE CONTRATO(
COD_CONTRATO     NUMBER(10),
NIF_CLIENTE      VARCHAR2(9), 
COD_DEPARTAMENTO NUMBER(4),
COD_CONTADOR     NUMBER(4)
   
);

ALTER TABLE CONTRATO
ADD CONSTRAINT CONTRATO_PK PRIMARY KEY(COD_CONTRATO, NIF_CLIENTE, COD_DEPARTAMENTO, COD_CONTADOR);
ALTER TABLE CONTRATO
ADD CONSTRAINT CONTRATO_CLIENTE_FK FOREIGN KEY(NIF_CLIENTE) REFERENCES CLIENTE(NIF);
ALTER TABLE CONTRATO
ADD CONSTRAINT CONTRATO_DEPARTAMENTO_FK FOREIGN KEY(COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO);
ALTER TABLE CONTRATO
ADD CONSTRAINT CONTRATO_CONTADOR_FK FOREIGN KEY(COD_CONTADOR) REFERENCES CONTADOR(COD_CONTADOR);

CREATE SEQUENCE SEQ_COD_CONTRATO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999999999
;