------------------------------------------------------
-- Autor       : IES HERMANOS MACHADO
-- Descripci�n : Script 2 CREACION TABLA CONTRATO - PROYECTO BBDD
-- Responsables : Fernando M�rquez Rodr�guez , Rafael Jos� Ossorio Lop�z, Victor Carrasco Artacho, Carlos Gonz�lez Ruiz, Gabriel Rodr�guez F�lix 
------------------------------------------------------

CREATE TABLE CONTRATO(
COD_CONTRATO     NUMBER(10),
NIF_CLIENTE      VARCHAR2(9), 
COD_DEPARTAMENTO NUMBER(4),
COD_CONTADOR     NUMBER(4)
   
);

ALTER TABLE CONTRATO
ADD CONSTRAINT CONTRATO_PK PRIMARY KEY(COD_CONTRATO, NIF_CLIENTE, COD_DEPARTAMENTO, COD_CONTADOR)
ADD CONSTRAINT CONTRATO_CLIENTE_FK FOREIGN KEY(NIF_CLIENTE) REFERENCES CLIENTE(NIF)
ADD CONSTRAINT CONTRATO_DEPARTAMENTO_FK FOREIGN KEY(COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO)
ADD CONSTRAINT CONTRATO_CONTADOR_FK FOREIGN KEY(COD_CONTADOR) REFERENCES CONTADOR(COD_CONTADOR);

CREATE SEQUENCE SEQ_COD_CONTRATO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999999999
;