------------------------------------------------------
-- Autor       : IES HERMANOS MACHADO
-- Descripción : Script 2 INSERCIÓN DATOS TABLA CONTADOR - PROYECTO BBDD
-- Responsables : Fernando Márquez Rodríguez , Rafael José Ossorio Lopéz, Victor Carrasco Artacho, Carlos González Ruiz, Gabriel Rodríguez Félix 
------------------------------------------------------

INSERT INTO CONTADOR(COD_CONTADOR,TIPO,CONSUMO) VALUES(1,'GAS',2346.23);
INSERT INTO CONTADOR(COD_CONTADOR,TIPO,CONSUMO) VALUES(2,'ELECTRICIDAD',7654.34);
INSERT INTO CONTADOR(COD_CONTADOR,TIPO,CONSUMO) VALUES(3,'ELECTRICIDAD',12234.8);
INSERT INTO CONTADOR(COD_CONTADOR,TIPO,CONSUMO) VALUES(4,'ELECTRICIDAD',9443.68);
INSERT INTO CONTADOR(COD_CONTADOR,TIPO,CONSUMO) VALUES(5,'GAS',6223.43);
INSERT INTO CONTADOR(COD_CONTADOR,TIPO,CONSUMO) VALUES(6,'GAS',6778.93);
INSERT INTO CONTADOR(COD_CONTADOR,TIPO,CONSUMO) VALUES(7,'GAS',54632.61);