------------------------------------------------------
-- Autor       : IES HERMANOS MACHADO
-- Descripción : Script 2 INSERCIÓN DATOS TABLA DEPARTAMENTO - PROYECTO BBDD
-- Responsables : Fernando Márquez Rodríguez , Rafael José Ossorio Lopéz, Victor Carrasco Artacho, Carlos González Ruiz, Gabriel Rodríguez Félix 
------------------------------------------------------

INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,NEMPLEADOS,JEFEDEPT) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Electricidad',3,1);
INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,NEMPLEADOS,JEFEDEPT) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Gas',1,3);
INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,NEMPLEADOS,JEFEDEPT) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Gas',2,5);
INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,NEMPLEADOS,JEFEDEPT) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Electricidad',4,2);
INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,NEMPLEADOS,JEFEDEPT) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Electricidad',5,4);