------------------------------------------------------
-- Autor       : IES HERMANOS MACHADO
-- Descripción : Script 2 INSERCIÓN DATOS TABLA DEPARTAMENTO - PROYECTO BBDD
-- Responsables : Fernando Márquez Rodríguez , Rafael José Ossorio Lopéz, Victor Carrasco Artacho, Carlos González Ruiz, Gabriel Rodríguez Félix 
------------------------------------------------------

INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,EMPLEADO_JEFE) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Electricidad',1);
INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,EMPLEADO_JEFE) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Gas',3);
INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,EMPLEADO_JEFE) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Gas',5);
INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,EMPLEADO_JEFE) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Electricidad',2);
INSERT INTO DEPARTAMENTO(COD_DEPARTAMENTO,ESPECIALIDAD,EMPLEADO_JEFE) VALUES(SEQ_COD_DEPARTAMENTO.NEXTVAL,'Electricidad',4);

COMMIT;