------------------------------------------------------
-- Autor       : IES HERMANOS MACHADO
-- Descripción : Script 2 INSERCIÓN CÓDIGO DEPARTAMENTO TABLA EMPLEADO - PROYECTO BBDD
-- Responsables : Fernando Márquez Rodríguez , Rafael José Ossorio Lopéz, Victor Carrasco Artacho, Carlos González Ruiz, Gabriel Rodríguez Félix 
------------------------------------------------------

UPDATE EMPLEADO SET COD_DEPARTAMENTO = 1 WHERE CODEMPLEADO = 1;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 4 WHERE CODEMPLEADO = 2;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 2 WHERE CODEMPLEADO = 3;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 5 WHERE CODEMPLEADO = 4;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 3 WHERE CODEMPLEADO = 5;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 4 WHERE CODEMPLEADO = 6;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 3 WHERE CODEMPLEADO = 7;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 1 WHERE CODEMPLEADO = 8;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 5 WHERE CODEMPLEADO = 9;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 5 WHERE CODEMPLEADO = 10;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 1 WHERE CODEMPLEADO = 11;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 2 WHERE CODEMPLEADO = 12;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 2 WHERE CODEMPLEADO = 13;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 2 WHERE CODEMPLEADO = 14;
UPDATE EMPLEADO SET COD_DEPARTAMENTO = 4 WHERE CODEMPLEADO = 15;

COMMIT;
