------------------------------------------------------
-- Autor       : IES HERMANOS MACHADO
-- Descripción : Script 2 INSERCIÓN DATOS TABLA CONTRATO - PROYECTO BBDD
-- Responsables : Fernando Márquez Rodríguez , Rafael José Ossorio Lopéz, Victor Carrasco Artacho, Carlos González Ruiz, Gabriel Rodríguez Félix 
------------------------------------------------------

INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'55555555E',2,7);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'88888888H',2,4);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'13135854J',1,2);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'11111111A',1,2);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'99999999I',1,3);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'77777777G',2,5);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'66666666F',1,2);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'22222222B',2,2);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'88888888H',2,7);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'33333333C',1,5);
INSERT INTO CONTRATO(COD_CONTRATO,NIF_CLIENTE,COD_DEPARTAMENTO,COD_CONTADOR) VALUES(SEQ_COD_CONTRATO.NEXTVAL,'44444444D',1,6);

COMMIT;